
ALTER TABLE crops DROP COLUMN IF EXISTS user_id;

ALTER TABLE crops ADD COLUMN IF NOT EXISTS batch_id VARCHAR(255) NOT NULL UNIQUE;
ALTER TABLE crops ADD COLUMN IF NOT EXISTS farmer_id VARCHAR(255) NOT NULL;
ALTER TABLE crops ADD COLUMN IF NOT EXISTS crop_name VARCHAR(255) NOT NULL;
ALTER TABLE crops ADD COLUMN IF NOT EXISTS price VARCHAR(255);
ALTER TABLE crops ADD COLUMN IF NOT EXISTS quantity VARCHAR(255);
ALTER TABLE crops ADD COLUMN IF NOT EXISTS description TEXT;
ALTER TABLE crops ADD COLUMN IF NOT EXISTS created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE crops 
ADD COLUMN IF NOT EXISTS stage VARCHAR(50) DEFAULT 'PLANTED',
ADD COLUMN IF NOT EXISTS trace_log TEXT;

